### PR TITLE
#75 sketch tool integration

### PR DESCRIPTION
**Pull request by AudreyLR**
Integrated SketchTool to intervention plan.

### CODE REVIEW

**Comment by iamkinetic** [comment]
Le npm install fail dans cette branche.   Pourquoi ça prendrait GTK?

    C:\Dev\survip-mobile>npm install
    
    > canvas@1.6.11 install C:\Dev\survip-mobile\node_modules\canvas
    > node-gyp rebuild
    
    
    C:\Dev\survip-mobile\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\frederic.catellier\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\User
    s\frederic.catellier\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
    Warning: Missing input files:
    C:\GTK\bin\zlib1.dll
    C:\GTK\bin\libexpat-1.dll
    C:\GTK\bin\libpng14-14.dll
    C:\GTK\bin\libcairo-2.dll
    C:\GTK\bin\libfontconfig-1.dll
    C:\GTK\bin\libfreetype-6.dll
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      Canvas.cc
      CanvasGradient.cc
      CanvasPattern.cc
      CanvasRenderingContext2d.cc
      color.cc
      Image.cc
      ImageData.cc
      init.cc
      win_delay_load_hook.cc
    c:\dev\survip-mobile\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Image.cc) [C:\Dev\survip-mobile\node_modules\canvas\build\canvas.vcxproj]
    c:\dev\survip-mobile\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasGradient.cc) [C:\Dev\survip-mobile\node_modules\canvas\build\canvas.vcxproj]
    c:\dev\survip-mobile\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Canvas.cc) [C:\Dev\survip-mobile\node_modules\canvas\build\canvas.vcxproj]
    c:\dev\survip-mobile\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\init.cc) [C:\Dev\survip-mobile\node_modules\canvas\build\canvas.vcxproj]
    c:\dev\survip-mobile\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\ImageData.cc) [C:\Dev\survip-mobile\node_modules\canvas\build\canvas.vcxproj]
    c:\dev\survip-mobile\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasPattern.cc) [C:\Dev\survip-mobile\node_modules\canvas\build\canvas.vcxproj]
    c:\dev\survip-mobile\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\Dev\survip-mobile\node_modules\canvas\build\canvas.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\frederic.catellier\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
    gyp ERR! stack     at emitTwo (events.js:126:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    gyp ERR! System Windows_NT 10.0.17134
    gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\frederic.catellier\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Dev\survip-mobile\node_modules\canvas
    gyp ERR! node -v v8.11.1
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok
    npm WARN @ngx-translate/core@10.0.1 requires a peer of @angular/core@>=6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
    npm WARN @ngx-translate/core@10.0.1 requires a peer of rxjs@>=6.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
    npm WARN @ngx-translate/http-loader@3.0.1 requires a peer of @angular/core@>=6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
    npm WARN @ngx-translate/http-loader@3.0.1 requires a peer of @angular/common@>=6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 (node_modules\canvas):
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 install: `node-gyp rebuild`
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by AudreyLR** [comment]
@iamkinetic J'ai modifié pour ouvrir l'outil dans une autre page.

**Comment by iamkinetic** [comment]
Ok.  Remettre le point dans "à tester" dans le board zenhub pour quand ce sera complètement terminé.

**Comment by iamkinetic** [comment]
Est-ce que les changements sont terminés?

**Comment by AudreyLR** [comment]
Presque. Les changements sont faits, mais les fonts de font-awesome ont été copiés directement dans assets au lieu d'utiliser le package npm. Je suis en train de modifier ça en ce moment.

**Comment by iamkinetic** [comment]
Conflits à régler avant qu'on puisse fermer ça.

**Comment by iamkinetic** [comment]
Ce sera le prochain pull request qui sera testé dans ce repo si les conflits sont rapidement réglés.

**Comment by iamkinetic** [comment]
Il serait tout à fait acceptable pour moi que le zoom soit fait dans une branche subséquente si tu veux arrêter de traîner cette branche.

Il faudra d'abord régler les conflits qui m'empêcheraient de merger celle-ci.

Dis-moi ce que tu en penses avant de commencer svp et qu'on soit sûr d'être sur la même longueur d'onde.

**Comment by AudreyLR** [comment]
Ah en effet ce n'est pas ce que j'avais compris! Je crois que ce serait en effet préférable que je règle les conflits sur celle-ci et que je fasse ça sur une branche suivante. Je règle les conflits à l'instant.

**Comment by iamkinetic** [comment]
Autres commentaires:
* Mettre le header en rouge comme le footer.
* Peut-être qu'on pourrait remplacer l'icône du pinceau par une palette de couleur?  Je pensais que ça servait à faire du free drawing au premier abord.

**Comment by iamkinetic** [comment]
Et on était pas supposé avoir des icônes custom comme un camion de pompier et des trucs du genre?

**Comment by iamkinetic** [comment]
Est-ce qu'on peut/pourra faire du free drawing comme dans ce démo: http://fabricjs.com/freedrawing

**Comment by iamkinetic** [comment]
Pinch to zoom + pan avec FabricJS:

https://stackoverflow.com/questions/45110576/fabricjs-touch-pan-zoom-entire-canvas

**Comment by iamkinetic** [comment]
Est-ce que tu te charges de créer les issues pour les trucs mentionnés?

**Comment by AudreyLR** [comment]
Les icônes ne sont pas sur cette branche, c'est pour ça qu'on ne les voit pas. Et oui, je peux créer les issues pour tout ça.

**Comment by iamkinetic** [comment]
Peux-tu me dire qu'est-ce qui a été fait dans cette branche et qu'est-ce qui le sera dans les autres histoire que je sache comment limiter mes tests?  

Merci!

**Comment by AudreyLR** [comment]
Dans cette branche: 
Outil de sketch qui comprend le texte, l'insertion de forme géométriques, la gestion des couleurs, le crop et le positionnement en Z des objets les uns par apports aux autres. Inclus aussi la sauvegarde.

Ce qui n'est pas dans cette branche: 
Le changements demandés hiers, les pictogrammes, la traduction à l'intérieur du component (voir pull-request du repo SketchTool) l'intégration pour risque particuliers et anomalies.

**Comment by iamkinetic** [comment]
Ok, tout est beau!

Pour les pull requests dans le repo SketchTool, peux-tu me mettre comme reviewer quand tu en as parce que j'ai pas trop tendance à aller voir là souvent pour être honnête.  Je n'avais pas vu qu'il y avait des pull requests en attente.

**Comment by AudreyLR** [comment]
@iamkinetic Je vais faire ça pour les prochains

**Pull request merged**
